const dinos: string[] = [
  'Albertosaurus',
  'Allosaurus',
  'Ankylosaurus',
  'Apatosaurus',
  'Brachiosaurus',
  'Carnotaurus',
  'Ceratops',
  'Changyuraptor',
  'Compsognathus',
  'Corythosaurus',
  'Deinonychus',
  'Diplodocus',
  'Edmontosaurus',
  'Euoplocephalus',
  'Gigantosaurus',
  'Helioceratops',
  'Herbstosaurus',
  'Heirosaurus',
  'Iguanadon',
  'Kentrosaurus',
  'Lesothosaurus',
  'Megalosaurus',
  'Notoceratops',
  'Ornithomimus',
  'Oviraptor',
  'Pachycephalosaurus',
  'Parasaurolophus',
  'Protoceratops',
  'Stegosaurus',
  'Spinosaurus',
  'Triceratops',
  'Tyrannosaurus',
  'Velociraptor',
  'Yangchuanosaurus'
]

export default dinos;